Drop glibc-specific header
`struct tm` is in `<time.h>` per POSIX, which is already included.

src/log.c:1:10: fatal error: 'bits/types/struct_tm.h' file not found
 #include <bits/types/struct_tm.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~